mkdir build
cmake -D WIN32=1 -G "Visual Studio 16" -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DJSON_WITH_EXAMPLE=False -DBUILD_TESTING=False -DBUILD_GMOCK=False -DJSONCPP_WITH_TESTS=False -A x64 --build ./ -B ./build 
pause